version: '3.8'

services:
  frontend:
    container_name: payment-checkout-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    env_file:
      - .env      
    environment:
      - NODE_ENV=production
    command: npm run start
    restart: always
