version: '3.8'

services:
  frontend:
    container_name: payment-checkout-frontend
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.example
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
