import type { Metadata } from "next";
import "./globals.css";
import { geistMono, geistSans } from "@/infrastructure/config/fonts";
import { CheckoutProvider } from "@/ui/context/CheckoutContext";

export const metadata: Metadata = {
	title: "Ecommerce App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<CheckoutProvider>
					{children}
				</CheckoutProvider>
			</body>
		</html>
	);
}
